(()=>{const $=id=>document.getElementById(id),TOKEN='gs_one_session',LANG_KEY='gs_one_language';const qLang=new URLSearchParams(location.search).get('lang');let lang=(qLang==='zh'||qLang==='en'?qLang:localStorage.getItem(LANG_KEY))||'en';
const text={zh:{sign:'登录',create:'注册账号',id:'用户名或邮箱',pw:'密码',user:'用户名',email:'邮箱（可选）',newpw:'密码（至少 8 位）',signin:'登录',register:'创建账号',hint:'登录状态保存在当前浏览器。Flux 等外部系统请使用 API Key，不要保存用户密码。',bad:'登录失败',regbad:'注册失败'},en:{sign:'Sign In',create:'Create Account',id:'Username or email',pw:'Password',user:'Username',email:'Email (optional)',newpw:'Password (8+ characters)',signin:'Sign In',register:'Create Account',hint:'Your session stays in this browser. External apps such as Flux should use API keys, not your password.',bad:'Sign in failed',regbad:'Registration failed'}};const errors={zh:{INVALID_CREDENTIALS:'用户名/邮箱或密码不正确',USERNAME_INVALID:'用户名需为 3–40 位字母、数字、点、下划线或横线',PASSWORD_LENGTH_INVALID:'密码至少 8 位',EMAIL_INVALID:'邮箱格式不正确',USERNAME_ALREADY_EXISTS:'用户名已存在',EMAIL_ALREADY_EXISTS:'邮箱已注册',SIGNUP_DISABLED:'当前未开放注册'},en:{INVALID_CREDENTIALS:'Incorrect username/email or password',USERNAME_INVALID:'Username must be 3–40 characters: letters, numbers, dot, underscore or hyphen',PASSWORD_LENGTH_INVALID:'Password must be at least 8 characters',EMAIL_INVALID:'Invalid email address',USERNAME_ALREADY_EXISTS:'Username already exists',EMAIL_ALREADY_EXISTS:'Email already registered',SIGNUP_DISABLED:'Sign-up is disabled'}};const msg=e=>errors[lang][e]||e;
function paint(){const t=text[lang];$('loginTab').textContent=t.sign;$('registerTab').textContent=t.create;$('idLabel').textContent=t.id;$('pwLabel').textContent=t.pw;$('userLabel').textContent=t.user;$('emailLabel').textContent=t.email;$('newPwLabel').textContent=t.newpw;$('loginBtn').textContent=t.signin;$('registerBtn').textContent=t.register;$('hint').textContent=t.hint;$('zh').classList.toggle('active',lang==='zh');$('en').classList.toggle('active',lang==='en');document.documentElement.lang=lang==='zh'?'zh-CN':'en'}
function save(j){localStorage.setItem(TOKEN,j.token);localStorage.setItem('gs_one_user',j.user.id);localStorage.setItem('gs_one_tenant',j.user.tenant_id||'default');localStorage.setItem('gs_one_username',j.user.username||'');const q=new URLSearchParams(location.search),next=q.get('next');location.replace(next&&next.startsWith('/')?next:'/library')}
async function call(path,body){const r=await fetch('/api/v1/auth/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.code||j.error||'REQUEST_FAILED');return j}
$('loginTab').onclick=()=>{$('loginTab').classList.add('active');$('registerTab').classList.remove('active');$('loginForm').classList.remove('hidden');$('registerForm').classList.add('hidden');$('error').textContent=''};$('registerTab').onclick=()=>{$('registerTab').classList.add('active');$('loginTab').classList.remove('active');$('registerForm').classList.remove('hidden');$('loginForm').classList.add('hidden');$('error').textContent=''};
$('loginForm').onsubmit=async e=>{e.preventDefault();$('error').textContent='';$('loginBtn').disabled=true;try{save(await call('login',{identifier:$('identifier').value,password:$('password').value}))}catch(err){$('error').textContent=(text[lang].bad)+': '+msg(err.message||String(err))}finally{$('loginBtn').disabled=false}};
$('registerForm').onsubmit=async e=>{e.preventDefault();$('error').textContent='';$('registerBtn').disabled=true;try{save(await call('register',{username:$('username').value,email:$('email').value,password:$('newPassword').value}))}catch(err){$('error').textContent=(text[lang].regbad)+': '+msg(err.message||String(err))}finally{$('registerBtn').disabled=false}};
$('zh').onclick=()=>{lang='zh';localStorage.setItem(LANG_KEY,lang);paint()};$('en').onclick=()=>{lang='en';localStorage.setItem(LANG_KEY,lang);paint()};
if(localStorage.getItem(TOKEN)){fetch('/api/v1/auth/me',{headers:{authorization:'Bearer '+localStorage.getItem(TOKEN)}}).then(r=>r.ok?r.json():null).then(j=>{if(j&&j.user)save({token:localStorage.getItem(TOKEN),user:j.user})}).catch(()=>{})}paint();})();
