const headers=()=>{const t=localStorage.getItem('gs_one_session')||'';return {'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})}};
let config=null, selectedMinor=2000;
const $=id=>document.getElementById(id);
function money(minor,currency='usd'){return new Intl.NumberFormat(undefined,{style:'currency',currency:String(currency).toUpperCase()}).format((Number(minor)||0)/100)}
async function json(url,opts={}){const r=await fetch(url,{...opts,headers:{...headers(),...(opts.headers||{})}});const j=await r.json();if(r.status===401){localStorage.removeItem('gs_one_session');location.href='/login.html?next='+encodeURIComponent(location.pathname+location.search);throw new Error('AUTH_REQUIRED')}if(!r.ok)throw new Error(j.error||j.code||`HTTP ${r.status}`);return j}
function pickAmount(minor){selectedMinor=minor;document.querySelectorAll('.amount').forEach(b=>b.classList.toggle('active',Number(b.dataset.minor)===minor));$('customAmount').value=''}
function renderConfig(c){config=c;const s=c.stripe;const w=c.local_wallet;$('currencyPill').textContent=s.currency.toUpperCase();$('balance').textContent=money(w.balance_minor,w.currency);$('amounts').innerHTML='';s.presets_minor.forEach(minor=>{const b=document.createElement('button');b.className='amount';b.dataset.minor=minor;b.textContent=money(minor,s.currency);b.onclick=()=>pickAmount(minor);$('amounts').appendChild(b)});pickAmount(s.presets_minor.includes(2000)?2000:s.presets_minor[0]);$('cardPay').disabled=!s.enabled;$('alipayPay').disabled=!s.enabled;if(!s.enabled)$('payError').textContent='Stripe 尚未配置：请在 Vercel 设置 STRIPE_SECRET_KEY 和 STRIPE_WEBHOOK_SECRET。'}
function chosenAmount(){const custom=Number($('customAmount').value);if(Number.isFinite(custom)&&custom>0)return Math.round(custom*100);return selectedMinor}
async function startPay(method){$('payError').textContent='';const amount=chosenAmount();const b=method==='card'?$('cardPay'):$('alipayPay');b.disabled=true;try{const j=await json('/api/payments/stripe/checkout',{method:'POST',body:JSON.stringify({method,amount_minor:amount,client_request_id:crypto.randomUUID()})});if(!j.checkout_url)throw new Error('Stripe did not return a checkout URL');location.href=j.checkout_url}catch(e){$('payError').textContent=e.message||String(e);b.disabled=!config?.stripe?.enabled}}
async function loadOrders(){try{const j=await json('/api/payments/orders');$('orders').innerHTML=j.orders.length?j.orders.map(o=>`<tr><td>${new Date(o.created_at).toLocaleString()}</td><td>${o.method==='alipay'?'Alipay':'Card'}</td><td><span class="tag">${o.status}</span></td><td class="right">${money(o.amount_minor,o.currency)}</td></tr>`).join(''):'<tr><td colspan="4" class="muted">暂无 Stripe 充值记录</td></tr>'}catch(e){$('orders').innerHTML=`<tr><td colspan="4" class="error">${e.message||e}</td></tr>`}}
async function handleReturn(){const q=new URLSearchParams(location.search),status=q.get('status'),sid=q.get('session_id');if(status==='cancelled'){const el=$('returnStatus');el.className='status show bad';el.textContent='支付已取消，没有入账。'}if(status==='success'&&sid){const el=$('returnStatus');el.className='status show';el.textContent='正在确认 Stripe 支付状态…';try{const j=await json('/api/payments/stripe/session/'+encodeURIComponent(sid));el.className='status show '+(j.order_status==='paid'?'ok':'bad');el.textContent=j.order_status==='paid'?`支付成功，已充值 ${money(j.amount_minor,j.currency)} SaaS Credits。`:`Stripe 当前状态：${j.payment_status} / ${j.order_status}`;history.replaceState(null,'','/payments.html')}catch(e){el.className='status show bad';el.textContent='支付状态确认失败：'+(e.message||e)}}}
$('cardPay').onclick=()=>startPay('card');$('alipayPay').onclick=()=>startPay('alipay');$('originalPay').onclick=()=>location.href='/library?recharge=1';$('customAmount').addEventListener('input',()=>document.querySelectorAll('.amount').forEach(b=>b.classList.remove('active')));
(async()=>{try{renderConfig(await json('/api/payments/config'));await handleReturn();await loadOrders();const c=await json('/api/payments/config');renderConfig(c)}catch(e){$('payError').textContent=e.message||String(e)}})();
