// Browser compatibility for the original Wails frontend. No Go runtime is used.
const METHODS=["AddManualEpisode","AppendSegmentPromptVersion","ApplyUpdateAndRestart","CanRestartPhysicalSplit","CancelArchitectAnalysis","CancelEditorPipeline","CancelTask","ChatStream","CheckForUpdates","ClearAssetImage","CreateAsset","CreateAssetAndUpload","CreateEmptyProject","CreateSaasDramaOnly","CreateWxPayOrder","DeleteAsset","DeleteScriptProject","DeleteSegment","DeleteSegmentPromptVersion","DetectScriptStructure","DownloadUpdate","DownloadVideoFile","FetchImageBase64","GenerateAssetPrompt","GenerateVideo","GetAIModels","GetAllAssets","GetAllScriptProjects","GetAppVersion","GetEpisodeSegments","GetFeaturePointInfo","GetMarketingActivities","GetModelSettings","GetProjectEpisodes","GetProjectRelations","GetProjectSettings","GetProjectSlices","GetSaaSScriptDetail","GetScriptProject","GetUpdateState","GetUserInfo","GetVideoFeaturePointSchema","GetWallet","GetWxPayConfig","InsertSegmentAfter","IsLoggedIn","ListFeaturePointDeductions","ListRechargePackages","ListRechargeRecords","ListSaaSScripts","ListTasks","ListVideoGenerations","ListVideoGenerationsByProject","Login","Logout","QueryWxPayOrderStatus","RefreshLLMConfig","ReinjectProjectRefs","ReinjectSegmentRefs","RenameScriptProject","RestartPhysicalSplit","SaveAssetPromptTabs","SaveEpisodeConfig","SaveProjectSettings","SegmentHasVideos","SelectScriptFile","SetSegmentActiveVersion","SetVideoGenerationFeatured","StartDirectorPipelineV2","StartEditorPipelineRange","StartPhysicalSplit","StartSubSplitEpisode","UpdateAssetDescription","UpdateAssetPosition","UpdateAssetStyleHint","UpdateEpisodeContent","UpdateEpisodeTitle","UpdateProjectModel","UpdateSegmentAssociatedRoles","UpdateSegmentDismissedRefs","UpdateSegmentNotes","UploadAssetAudio","UploadAssetImage"];
const authToken=()=>localStorage.getItem('gs_one_session')||'';
const authHeaders=()=>authToken()?{authorization:'Bearer '+authToken()}:{};
function persistUser(user){if(!user)return;localStorage.setItem('gs_one_user',user.id||'');localStorage.setItem('gs_one_tenant',user.tenant_id||user.tenantId||'default');localStorage.setItem('gs_one_username',user.username||'')}
function clearAuth(){localStorage.removeItem('gs_one_session');localStorage.removeItem('gs_one_user');localStorage.removeItem('gs_one_tenant');localStorage.removeItem('gs_one_username')}
async function invoke(method,args){
  const r=await fetch('/api/app/'+encodeURIComponent(method),{method:'POST',headers:{'content-type':'application/json',...authHeaders()},body:JSON.stringify({args})});
  const j=await r.json().catch(()=>({success:false,error:'INVALID_JSON_RESPONSE'}));
  if(r.status===401){clearAuth();if(!location.pathname.includes('login'))location.href='/login.html?next='+encodeURIComponent(location.pathname+location.search);return {success:false,code:'AUTH_REQUIRED'}}
  return j;
}
const App={};for(const m of METHODS)App[m]=(...args)=>invoke(m,args);
App.IsLoggedIn=async()=>{const t=authToken();if(!t)return false;try{const r=await fetch('/api/v1/auth/me',{headers:authHeaders(),cache:'no-store'});if(!r.ok)return false;const j=await r.json();persistUser(j.user);return Boolean(j.success&&j.user)}catch{return false}};
App.Login=async(identifier,password)=>{try{const r=await fetch('/api/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identifier,password})});const j=await r.json();if(!r.ok||!j.success)return j;localStorage.setItem('gs_one_session',j.token);persistUser(j.user);return {success:true,authenticated:true,user:j.user}}catch(e){return {success:false,error:e?.message||String(e)}}};
App.Logout=async()=>{const t=authToken();try{if(t)await fetch('/api/v1/auth/logout',{method:'POST',headers:authHeaders()})}catch{}clearAuth();location.href='/login.html';return true};
// Local-video autosave hook.
for(const listMethod of ['ListVideoGenerations','ListVideoGenerationsByProject']){App[listMethod]=async(...args)=>{const rows=await invoke(listMethod,args);if(Array.isArray(rows)&&window.GSLocalVideoStorage)window.GSLocalVideoStorage.autoSaveGenerations(rows).catch(()=>{});return rows;};}
App.DownloadVideoFile=async(url,filename)=>window.GSLocalVideoStorage?window.GSLocalVideoStorage.saveUrl(url,filename):({success:false,error:'LOCAL_VIDEO_STORAGE_UNAVAILABLE'});
App.SelectScriptFile=()=>new Promise((resolve,reject)=>{const i=document.createElement('input');i.type='file';i.accept='.txt,.docx';i.onchange=()=>{const f=i.files&&i.files[0];if(!f)return resolve(null);const r=new FileReader();r.onload=()=>resolve({name:f.name,size:f.size,type:f.type,data_url:String(r.result)});r.onerror=()=>reject(r.error);r.readAsDataURL(f)};i.click()});
window.go=window.go||{};window.go.main=window.go.main||{};window.go.main.App=App;
window.runtime=window.runtime||{};window.runtime.EventsOn=(name,cb)=>()=>{};window.runtime.EventsOnMultiple=(name,cb)=>()=>{};window.runtime.EventsOff=()=>{};window.runtime.EventsEmit=()=>{};window.runtime.BrowserOpenURL=(u)=>window.open(u,'_blank');window.runtime.WindowToggleMaximise=()=>{};
(function installLocalVideoShortcut(){function add(){if(document.getElementById('gsone-local-video-shortcut')||location.pathname.includes('local-videos'))return;const b=document.createElement('button');b.id='gsone-local-video-shortcut';b.type='button';b.style.cssText='position:fixed;right:18px;bottom:66px;z-index:180;border:1px solid rgba(52,211,153,.3);border-radius:12px;padding:10px 14px;background:#0b2a28;color:#c7fff0;font:700 12px system-ui;box-shadow:0 12px 35px rgba(0,0,0,.35);cursor:pointer';const paint=()=>{const st=window.GSLocalVideoStorage&&window.GSLocalVideoStorage.getStatus?window.GSLocalVideoStorage.getStatus():null;if(!st){b.textContent='📁 本地视频库';return}if(!st.supported){b.textContent='⚠️ 本地存储不支持';b.style.background='#3a1c20'}else if(st.lastError){b.textContent='⚠️ 视频目录 ERROR';b.style.background='#3a1c20'}else if(!st.configured){b.textContent='📁 选择视频目录';b.style.background='#30280e'}else if(!st.libraryReady){b.textContent='🔐 视频目录需授权';b.style.background='#30280e'}else{b.textContent='📁 本地视频库';b.style.background='#0b2a28'}};b.onclick=()=>{location.href='/local-videos'};document.body.appendChild(b);paint();if(window.GSLocalVideoStorage&&window.GSLocalVideoStorage.onStatus)window.GSLocalVideoStorage.onStatus(paint)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add,{once:true});else add()})();
(function installSaasPaymentShortcut(){function add(){if(document.getElementById('gsone-saas-payment-shortcut')||location.pathname.includes('payments.html'))return;const b=document.createElement('button');b.id='gsone-saas-payment-shortcut';b.type='button';b.textContent='💳 Card / Alipay';b.style.cssText='position:fixed;right:18px;bottom:18px;z-index:180;border:1px solid rgba(148,163,184,.25);border-radius:12px;padding:10px 14px;background:#111827;color:#fff;font:600 12px system-ui;box-shadow:0 12px 35px rgba(0,0,0,.35);cursor:pointer';b.onclick=()=>{location.href='/payments.html'};document.body.appendChild(b)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add,{once:true});else add()})();
